appus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('bases.urls','bases'), namespace='bases')),  
    path('emp/', include(('emp.urls','emp'), namespace='emp')),
     
    path('admin/', admin.site.urls),
]

emp/urls.py
from django.urls import path

from .views import TipoDocumentoView, TipoDocumentoNew, TipoDocumentoEdit, SocialSecView, SocialSecNew, SocialSecEdit, \
                   EpsNew, EpsView, EpsEdit, SexoView, SexoNew, SexoEdit, EstadoCivilView, EstadoCivilNew, \
                   EstadoCivilEdit, CiudadNew, CiudadView, CiudadEdit, ProfesionView, ProfesionNew, ProfesionEdit, \
                   NacionalidadView, NacionalidadEdit, NacionalidadNew, EmpleadoView, EmpleadoNew, EmpleadoEdit 

urlpatterns = [
 
    path('documentos/',TipoDocumentoView.as_view(), name='documento_list'),
    path('documentos/new',TipoDocumentoNew.as_view(), name='documento_new'),
    path('documentos/edit/<int:pk>',TipoDocumentoEdit.as_view(), name='documento_edit'),

    path('socials/',SocialSecView.as_view(), name='social_list'),
    path('socials/new',SocialSecNew.as_view(), name='social_new'),
    path('socials/edit/<int:pk>',SocialSecEdit.as_view(), name='social_edit'),

    path('eps/',EpsView.as_view(), name='eps_list'),
    path('eps/new',EpsNew.as_view(), name='eps_new'),
    path('eps/edit/<int:pk>',EpsEdit.as_view(), name='eps_edit'),

    path('estadocivil/',EstadoCivilView.as_view(), name='estadocivil_list'),
    path('estadocivil/new',EstadoCivilNew.as_view(), name='estadocivil_new'),
    path('estadocivil/edit/<int:pk>',EstadoCivilEdit.as_view(), name='estadocivil_edit'),

    path('genero/',SexoView.as_view(), name='genero_list'),
    path('genero/new',SexoNew.as_view(), name='genero_new'),
    path('genero/edit/<int:pk>',SexoEdit.as_view(), name='genero_edit'),

    path('ciudad/',CiudadView.as_view(), name='ciudad_list'),
    path('ciudad/new',CiudadNew.as_view(), name='ciudad_new'),
    path('ciudad/edit/<int:pk>',CiudadEdit.as_view(), name='ciudad_edit'),

    path('profesion/',ProfesionView.as_view(), name='profesion_list'),
    path('profesion/new',ProfesionNew.as_view(), name='profesion_new'),
    path('profesion/edit/<int:pk>',ProfesionEdit.as_view(), name='profesion_edit'),

    path('nacionalidad/',NacionalidadView.as_view(), name='nacionalidad_list'),
    path('nacionalidad/new',NacionalidadNew.as_view(), name='nacionalidad_new'),
    path('nacionalidad/edit/<int:pk>',NacionalidadEdit.as_view(), name='nacionalidad_edit'),

    path('empleado/',EmpleadoView.as_view(), name='empleado_list'),
    path('empleado/new',EmpleadoNew.as_view(), name='empleado_new'),
    path('empleado/edit/<int:pk>',EmpleadoEdit.as_view(), name='empleado_edit'),



]

bases/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ClaseModelo(models.Model):

    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now_add=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True,null=True)

   
   # Para que no lo tenga en cuenta en una migracion pero si hereda.

    class Meta:
        abstract=True

emp/models.py
from django.db import models

from bases.models import ClaseModelo

# Create your models here.
class TipoDocumento(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Tipo de Documento',
        unique=True 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(TipoDocumento, self).save()

    class Meta:
        verbose_name_plural = "Documentos"

class SocialSec(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='SocialSec',
        unique=True 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SocialSec, self).save()

    class Meta:
        verbose_name_plural = "Socials"

class Eps(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Eps',
        unique=True 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Eps, self).save()

    class Meta:
        verbose_name_plural = "Eps"

class EstadoCivil(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='EstadoCivil',
        unique=True 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(EstadoCivil, self).save()

    class Meta:
        verbose_name_plural = "Estado Civil"


class Sexo(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Sexo',
        unique=True 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Sexo, self).save()

    class Meta:
        verbose_name_plural = "Sexo"

class Ciudad(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Ciudades y estados',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Ciudad, self).save()

    class Meta:
        verbose_name_plural = "Ciudades y estados"

class Profesion(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Tipo de profesion',
        unique=True 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Profesion, self).save()

    class Meta:
        verbose_name_plural = "Profesion"

class Nacionalidad(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Seleccione Nacionalidad',
        unique=True 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Nacionalidad, self).save()

    class Meta:
        verbose_name_plural = "Nacionalidad"


class Empleado(ClaseModelo):

    numero_identificacion = models.CharField(
        max_length=30,
        help_text='Numero de identificación',
        unique=True 
    )
  
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    lugar_nacimiento = models.CharField(max_length=30)
    direccion_residencia = models.CharField(max_length=50)
    barrio = models.CharField(max_length=50)
    numero_telefonico = models.CharField(max_length=15)
    correo_electronico = models.CharField(max_length=30)
    cargo = models.CharField(max_length=30)
    contacto_emergencia = models.CharField(max_length=30)
    numero_telefonico2 = models.CharField(max_length=15)
    

    tipo_documento = models.ForeignKey(TipoDocumento, on_delete=models.CASCADE)
    ciudad_resident = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    social_security = models.ForeignKey(SocialSec, on_delete=models.CASCADE)
    eps = models.ForeignKey(Eps, on_delete=models.CASCADE)
    nacionalidad = models.ForeignKey(Nacionalidad, on_delete=models.CASCADE)
    profesion = models.ForeignKey(Profesion, on_delete=models.CASCADE)
    estado_civil = models.ForeignKey(EstadoCivil, on_delete=models.CASCADE)
    sexo = models.ForeignKey(Sexo, on_delete=models.CASCADE) 

    def __str__(self):
        return '{}'.format(self.numero_identificacion)
    
    def save(self):
        self.numero_identificacion = self.numero_identificacion.upper()
        super(Empleado,self).save()
    
    class Meta:
        verbose_name_plural = "Empleados"
        unique_together = ('numero_identificacion','apellidos')
        
 

emp/forms.py
from django import forms


from .models import TipoDocumento, SocialSec, Eps, EstadoCivil, Sexo, Ciudad, \
    Profesion, Nacionalidad, Empleado

class TipoDocumentoForm(forms.ModelForm):
    
    class Meta:
        model  = TipoDocumento
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción tipo de documento",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields): 
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class SocialSecForm(forms.ModelForm):
    class Meta:
        model  = SocialSec
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción Social",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class EpsForm(forms.ModelForm):
    class Meta:
        model  = Eps
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción Eps",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class EstadoCivilForm(forms.ModelForm):
    class Meta:
        model  = EstadoCivil
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción Estado civil",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
class SexoForm(forms.ModelForm):
    class Meta:
        model  = Sexo
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción Genero",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
class CiudadForm(forms.ModelForm):
    class Meta: 
        model  = Ciudad
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción Ciudades y Municipios",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class ProfesionForm(forms.ModelForm):
    class Meta:
        model  = Profesion
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción profesion de la persona",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class NacionalidadForm(forms.ModelForm):
    class Meta:
        model  = Nacionalidad
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción Nacionalidad",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class EmpleadoForm(forms.ModelForm):
    fecha_vigencia_licencia = forms.DateInput()
    fecha_nacimiento = forms.DateInput()
    class Meta:
        model= Empleado
        fields=['numero_identificacion','nombres','apellidos','fecha_nacimiento', \
                'lugar_nacimiento','direccion_residencia','barrio','numero_telefonico', \
                'correo_electronico', 'estado', 'social_security', \
                'contacto_emergencia','numero_telefonico2','tipo_documento','ciudad_resident', \
                'eps','nacionalidad','profesion','estado_civil', 'cargo', \
                'sexo']

        exclude = ['um','fm','uc','fc']
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    # self.fields['fecha_vigencia_licencia'].widget.attrs['readonly'] = True
    # self.fields['fecha_nacimiento'].widget.attrs['readonly'] = True

       

emp/templates/emp/ciudad_form.html
{% extends 'base/base.html' %}
{% block page_content %}
<form method="POST" class="form-inline">
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-90 py-2">
        {% else %}
        <div class="card border-left-success shadow h-90 py-2">
        {% endif %}
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    {% if obj %} Editar {% else %} Nueva tipo {% endif %} Ciudad
                </div>
                <div class="dropdown-divider"></div>
                {% csrf_token %}
                <div class="row">
                    <div class="col-10">
                        <div class="input-group">
                            {{ form.descripcion }}
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="input-group">
                            <label for="id_estado">Estado</label>
                           
                            {{ form.estado }}
                        </div>
                    </div>        
                    <!-- {{ form.as_p }} -->
                </div>
                <div class="dropdown-divider"></div>
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                        <a href="{% url 'emp:ciudad_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <!-- <i class="far fa-calendar-plus fa-2x text-gray-300"></i> -->
            </div>
            </div>
        </div>
        </div>
    </div>
</form>
{% endblock %}

emp/templates/emp/documento_form.html
{% extends 'base/base.html' %}
{% block page_content %}
<form method="POST" class="form-inline">
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-90 py-2">
        {% else %}
        <div class="card border-left-success shadow h-90 py-2">
        {% endif %}
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    {% if obj %} Editar {% else %} Nuevo tipo {% endif %} Documento
                </div>
                <div class="dropdown-divider"></div>
                {% csrf_token %}
                <div class="row">
                    <div class="col-10">
                        <div class="input-group">
                            {{ form.descripcion }}
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="input-group">
                            <label for="id_estado">Estado</label>
                           
                            {{ form.estado }}
                        </div>
                    </div>        
                    <!-- {{ form.as_p }} -->
                </div>
                <div class="dropdown-divider"></div>
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                        <a href="{% url 'emp:documento_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <!-- <i class="far fa-calendar-plus fa-2x text-gray-300"></i> -->
            </div>
            </div>
        </div>
        </div>
    </div>
</form>
{% endblock %}

emp/templates/emp/documento_list.html
{% extends  'base/base.html' %}

{% block  page_content %}

<!-- Dropdown Card Example -->
<div class="card card-header-actions">
    <div class="card-header">
        Crud de creación tipos de documento
        <div class="dropdown no-caret">
            <button class="btn btn-transparent-dark btn-icon dropdown-toggle" id="dropdownMenuButton" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i data-feather="more-vertical"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right animated--fade-in-up" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'emp:documento_new' %}"><i class="far fa-calendar-plus"></i>Nuevo</a>
                <a class="dropdown-item" href="#!">Cancelar</a>
                <a class="dropdown-item" href="#!">Guardar</a>
            </div>
        </div>
    </div>
    
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
        <div class="alert alert-info">No existen tipo de documentos</div>    
    
      {% else %}
        <table class="table table-sm table-bordered">
            <thead>
                <th style="text-align: center">Id</th>
                <th style="text-align: center">Descripcion</th>
                <th style="text-align: center">Estado</th>
                <!-- <th>Fecha creado</th> -->
                <th style="text-align: center" >Fecha modificado</th>
                <th style="text-align: center" class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}

                <tr>
                    <td>{{ item.id  }}</td>
                    <td>{{ item.descripcion  }}</td>
                    <td>{{ item.estado|yesno:"Activo,Inactivo"  }}</td>
                    <!-- <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td> -->
                    <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                    <td style="text-align: center" >
                         <a href="{% url 'emp:documento_edit' item.id %}" class="btn btn-warning btn-circle" role="button"> <i class="far fa-edit"></i></a>
                         <!-- <button type="button" class="btn btn-xm btn-danger" data-toggle="popover" title="Información importante!!" data-content="Tener cuidado al borrar registro, recuerde solo inactivar">Info</button> -->
                         <a href="#" class="btn btn-success btn-circle" role="button"> <i class="far fa-eye"></i></a>  
                    </td>

                </tr>
                {% endfor %}

            </tbody>

        </table>
        {% endif %}  
    </div>
</div>

{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

emp/templates/emp/empleado_list.html
{% extends  'base/base.html' %}

{% block  page_content %}

<!-- Dropdown Card Example -->
<div class="card card-header-actions">
    <div class="card-header">
        Creación de Empleados
        <div class="dropdown no-caret">
            <button class="btn btn-transparent-dark btn-icon dropdown-toggle" id="dropdownMenuButton" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i data-feather="more-vertical"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right animated--fade-in-up" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'emp:empleado_new' %}"><i class="far fa-calendar-plus"></i>Nuevo</a>
                <a class="dropdown-item" href="#!">Cancelar</a>
            </div>
        </div>
    </div>
    
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
        <div class="alert alert-info">No existen empleados</div>    
    
      {% else %}
        <table class="table table-sm table-bordered">
            <thead>
                <th>Num.Identificación</th> 
                <th>Nombres</th>       
                <th>Apellidos</th>
                <th>Num.Telefonico</th>
                <th>Cargo</th>
                <th>Estado</th>
                <th style="text-align: center" class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}

                <tr>
                    <td>{{ item.numero_identificacion }}</td>
                    <td>{{ item.nombres }}</td>
                    <td>{{ item.apellidos }}</td>
                    <td>{{ item.numero_telefonico }}</td>
                    <td>{{ item.cargo }}</td>
                    <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                    <td style="text-align: center" >
                         <a href="{% url 'emp:empleado_edit' item.id %}" class="btn btn-warning btn-circle" role="button"> <i class="far fa-edit"></i></a>
                         <!-- <button type="button" class="btn btn-xm btn-danger" data-toggle="popover" title="Información importante!!" data-content="Tener cuidado al borrar registro, recuerde solo inactivar">Info</button> -->
                         <a href="#" class="btn btn-success btn-circle" role="button"> <i class="far fa-eye"></i></a>  
                    </td>

                </tr>
                {% endfor %}

            </tbody>

        </table>
        {% endif %}  
    </div>
</div>

{% endblock %}

{% block js_page %}
<script>
    // Call the dataTables jQuery plugin
  //   para realizar traduccion de labels
 
    $(function () {

        $("#id_ffecha_vigencia_licencia, #id_fecha_nacimiento").datetimepicker({
            format: 'Y-m-d',
            timepicker:false
        });  
  
  $(document).ready(function() {
      $('.table').DataTable({
        "language": {
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ registros",
          "sZeroRecords": "No se encontraron resultados",
          "sEmptyTable": "Ningún dato disponible en esta tabla",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
              "sFirst": "<span class='fa fa-angle-double-left'></span>",
              "sLast": "<span class='fa fa-angle-double-right'></span>",
              "sNext": "<span class='fa fa-angle-right'></span>",
              "sPrevious": "<span class='fa fa-angle-left'></span>"
          },
          "oAria": {
              "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
        }
      });
    });
    </script>
  {% endblock %}

emp/templates/emp/eps_form.html
{% extends 'base/base.html' %}
{% block page_content %}
<form method="POST" class="form-inline">
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-90 py-2">
        {% else %}
        <div class="card border-left-success shadow h-90 py-2">
        {% endif %}
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    {% if obj %} Editar {% else %} Nueva {% endif %} Eps    </div>
                <div class="dropdown-divider"></div>
                {% csrf_token %}
                <div class="row">
                    <div class="col-10">
                        <div class="input-group">
                            {{ form.descripcion }}
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="input-group">
                            <label for="id_estado">Estado</label>
                           
                            {{ form.estado }}
                        </div>
                    </div>        
                    <!-- {{ form.as_p }} -->
                </div>
                <div class="dropdown-divider"></div>
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                        <a href="{% url 'emp:eps_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <!-- <i class="far fa-calendar-plus fa-2x text-gray-300"></i> -->
            </div>
            </div>
        </div>
        </div>
    </div>
</form>
{% endblock %}

emp/templates/emp/eps_list.html
{% extends  'base/base.html' %}

{% block  page_content %}

<!-- Dropdown Card Example -->
<div class="card card-header-actions">
    <div class="card-header">
        Crud de creación Eps
        <div class="dropdown no-caret">
            <button class="btn btn-transparent-dark btn-icon dropdown-toggle" id="dropdownMenuButton" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i data-feather="more-vertical"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right animated--fade-in-up" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'emp:eps_new' %}"><i class="far fa-calendar-plus"></i>Nuevo</a>
                <a class="dropdown-item" href="#!">Cancelar</a>
                <a class="dropdown-item" href="#!">Guardar</a>
            </div>
        </div>
    </div>
    
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
        <div class="alert alert-info">No existe Eps's</div>    
    
      {% else %}
        <table class="table table-sm table-bordered">
            <thead>
                <th style="text-align: center">Id</th>
                <th style="text-align: center">Descripcion</th>
                <th style="text-align: center">Estado</th>
                <!-- <th>Fecha creado</th> -->
                <th style="text-align: center" >Fecha modificado</th>
                <th style="text-align: center" class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}

                <tr>
                    <td>{{ item.id  }}</td>
                    <td>{{ item.descripcion  }}</td>
                    <td>{{ item.estado|yesno:"Activo,Inactivo"  }}</td>
                    <!-- <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td> -->
                    <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                    <td style="text-align: center" >
                         <a href="{% url 'emp:eps_edit' item.id %}" class="btn btn-warning btn-circle" role="button"> <i class="far fa-edit"></i></a>
                         <!-- <button type="button" class="btn btn-xm btn-danger" data-toggle="popover" title="Información importante!!" data-content="Tener cuidado al borrar registro, recuerde solo inactivar">Info</button> -->
                         <a href="#" class="btn btn-success btn-circle" role="button"> <i class="far fa-eye"></i></a>  
                    </td>

                </tr>
                {% endfor %}

            </tbody>

        </table>
        {% endif %}  
    </div>
</div>

{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}